[project]
name = "QingmaKiller"
version = "1.1.0"
description = "青马易战自动答题工具"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
    { name = "Xuuyuan", email = "nexfoun@gmail.com" }
]
dependencies = [
    "pycryptodome>=3.21.0",
    "requests>=2.32.3",
    "beautifulsoup4>=4.12.3",
    "loguru>=0.7.2",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["api", "auth", "bank", "cli", "config", "logger", "main", "paths", "solver", "tiku", "utils", "winproc"]